name: e_store
description: "A new Professional Flutter E-Commerce App with Firebase as Backend project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

#------------ PACKAGES ------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages

  # Icons
  iconsax:
  cupertino_icons: ^1.0.6

  # State Management
  get:

  # Product Specific

#------------ PACKAGES End ------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #------------ LOCAL ASSETS ------------#
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/brands/

  #------------ LOCAL FONTS ------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/coolvetica rg.otf
          weight: 400
        - asset: assets/fonts/coolvetica rg it.otf
          weight: 400
          style: italic
    #------------ LOCAL FONTS END ------------#